import type {Metadata} from "next";
import "./globals.css";
import Header from "@/app/ui/header";
import {inter} from "@/app/ui/fonts";

export const metadata: Metadata = {
    title: "Library",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
            <body className={`${inter.className} antialiased flex justify-center`}>
                <div className="w-full max-w-[1280px] flex flex-col mx-10 mt-4">
                    <Header/>
                    {children}
                </div>
            </body>
        </html>
    );
}
